import { Category, Product, TontineGroup } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-electromenager',
    name: 'Électroménager',
    slug: 'electromenager',
    description: 'Réfrigérateurs, congélateurs, lave-linge et cuisinières de grandes marques garanties.',
    icon: 'Refrigerator',
    displayOrder: 1,
    isActive: true,
    itemCount: 14,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-tv-audio',
    name: 'Téléviseurs & Audio',
    slug: 'tv-audio',
    description: 'Smart TV UHD 4K, barres de son immersives et équipements audiovisuels.',
    icon: 'Tv',
    displayOrder: 2,
    isActive: true,
    itemCount: 10,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-climatisation',
    name: 'Climatisation & Ventilation',
    slug: 'climatisation',
    description: 'Climatiseurs split inverter économiques, rafraîchisseurs et ventilateurs puissants.',
    icon: 'Wind',
    displayOrder: 3,
    isActive: true,
    itemCount: 8,
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-mobilier',
    name: 'Mobilier de Maison',
    slug: 'mobilier',
    description: 'Salons en velours et cuir, salles à manger, lits capitonnés et rangements modernes.',
    icon: 'Armchair',
    displayOrder: 4,
    isActive: true,
    itemCount: 12,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-cuisine-maison',
    name: 'Équipements & Petit Ménager',
    slug: 'equipements-maison',
    description: 'Micro-ondes, fontaines à eau, mixeurs, fers à repasser et accessoires indispensables.',
    icon: 'Coffee',
    displayOrder: 5,
    isActive: true,
    itemCount: 18,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-hisense-fridge-260',
    name: 'Réfrigérateur Combiné No Frost Hisense 260L',
    slug: 'refrigerateur-combine-no-frost-hisense-260l',
    description: 'Réfrigérateur combiné haut de gamme avec technologie No Frost intégrée, distributeur d\'eau en façade et compresseur tropicalisé ultra-silencieux.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Hisense',
    model: 'RD-35WR',
    priceCash: 215000,
    priceInstallment: 235000,
    priceTontine: 228000,
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Capacité 260 Litres',
      'Technologie Total No Frost',
      'Distributeur d\'eau fraîche externe',
      'Éclairage LED basse consommation',
      'Garantie 2 ans constructeur',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'prod-samsung-tv-55-4k',
    name: 'Smart TV Samsung 55" Crystal UHD 4K',
    slug: 'smart-tv-samsung-55-crystal-uhd-4k',
    description: 'Une qualité d\'image saisissante avec le processeur Crystal 4K, compatible Netflix, YouTube, Canal+, et son Dolby Digital immersif.',
    categoryId: 'cat-tv-audio',
    categoryName: 'Téléviseurs & Audio',
    brand: 'Samsung',
    model: 'UA55CU7000',
    priceCash: 295000,
    priceInstallment: 320000,
    priceTontine: 310000,
    stock: 9,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Écran 55 pouces (140 cm) 4K Ultra HD',
      'HDR 10+ et Dynamic Color',
      'Système Tizen OS avec toutes vos applications',
      '3 ports HDMI, 1 port USB, Bluetooth & Wi-Fi',
      'Garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 20,
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'prod-midea-split-15cv',
    name: 'Climatiseur Split Midea 1.5 CV Inverter Tropicalisé',
    slug: 'climatiseur-split-midea-1-5-cv-inverter',
    description: 'Climatiseur split inverter haute efficacité énergétique, conçu spécialement pour le climat chaud et humide d\'Abidjan et des régions de Côte d\'Ivoire.',
    categoryId: 'cat-climatisation',
    categoryName: 'Climatisation & Ventilation',
    brand: 'Midea',
    model: 'MSAF-12CRDN1',
    priceCash: 235000,
    priceInstallment: 255000,
    priceTontine: 245000,
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Puissance 1.5 CV (12 000 BTU)',
      'Technologie Inverter économie jusqu\'à 60% d\'énergie',
      'Gaz écologique R410A / R32',
      'Filtre antibactérien haute densité',
      'Garantie 3 ans compresseur',
    ],
    warrantyMonths: 36,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'prod-solstar-cooker-4f',
    name: 'Cuisinière 4 Feux Inox Solstar avec Four Grill',
    slug: 'cuisiniere-4-feux-inox-solstar',
    description: 'Cuisinière à gaz en acier inoxydable robuste avec 4 brûleurs haute puissance, grand four émaillé et grille chauffante.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Solstar',
    model: 'FS-6060-IX',
    priceCash: 145000,
    priceInstallment: 160000,
    priceTontine: 155000,
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Finition tout inox durable',
      '4 brûleurs à allumage électrique',
      'Four à gaz spacieux avec rôtissoire',
      'Couvercle en verre trempé de protection',
      'Garantie 1 an',
    ],
    warrantyMonths: 12,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 4,
    installmentMinDepositPercent: 30,
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'prod-lg-washer-8kg',
    name: 'Lave-linge Automatique LG 8kg Direct Drive',
    slug: 'lave-linge-automatique-lg-8kg',
    description: 'Machine à laver automatique avec moteur Inverter Direct Drive ultra fiable, lavage vapeur anti-allergène et essorage 1200 tours/min.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'LG',
    model: 'FH2J3TDNP0',
    priceCash: 310000,
    priceInstallment: 335000,
    priceTontine: 325000,
    stock: 6,
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Capacité de lavage 8 kg',
      'Moteur Inverter Direct Drive garanti 10 ans',
      'Programme rapide 30 minutes',
      'Économie d\'eau et d\'électricité A+++',
      'Garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 20,
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'prod-penta-salon-confort',
    name: 'Salon d\'Angle Modulaire 6 Places PENTA Confort',
    slug: 'salon-angle-modulaire-6-places-penta',
    description: 'Ensemble salon d\'angle moderne en tissu velours antitaches avec mousse haute résilience grand confort, table basse assortie offerte.',
    categoryId: 'cat-mobilier',
    categoryName: 'Mobilier de Maison',
    brand: 'PENTA Living',
    model: 'PL-ANG-06',
    priceCash: 450000,
    priceInstallment: 490000,
    priceTontine: 480000,
    stock: 4,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Structure en bois massif traité',
      'Revêtement velours déperlant antitaches',
      'Coussins déhoussables et lavables',
      'Méridienne réversible droite/gauche',
      'Fabrication soignée garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 8,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'prod-westpool-freezer-200',
    name: 'Congélateur Coffre Westpool 200 Litres Tropicalisé',
    slug: 'congelateur-coffre-westpool-200l',
    description: 'Congélateur horizontal super isolé maintenant le froid jusqu\'à 48h en cas de coupure d\'électricité. Serrure de sécurité et panier inclus.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Westpool',
    model: 'BD-200',
    priceCash: 175000,
    priceInstallment: 190000,
    priceTontine: 185000,
    stock: 11,
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Capacité 200 Litres',
      'Consommation énergétique basse A+',
      'Thermostat réglable façade',
      'Panier suspendu amovible',
      'Garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'prod-fontaine-eau-penta',
    name: 'Fontaine Distributrice d\'Eau Chaude & Froide PENTA',
    slug: 'fontaine-distributrice-eau-penta',
    description: 'Distributeur d\'eau sur pied élégant avec compartiment réfrigéré inférieur, robinets sécurisés eau chaude et froide.',
    categoryId: 'cat-cuisine-maison',
    categoryName: 'Équipements & Petit Ménager',
    brand: 'PENTA Appliances',
    model: 'WD-201',
    priceCash: 65000,
    priceInstallment: 75000,
    priceTontine: 70000,
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    ],
    features: [
      'Double robinet chaud & froid',
      'Bac réfrigéré de stockage inférieur',
      'Sécurité enfant pour l\'eau chaude',
      'Compresseur silencieux',
      'Garantie 1 an',
    ],
    warrantyMonths: 12,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: false,
    installmentMaxMonths: 3,
    installmentMinDepositPercent: 30,
    isActive: true,
    isFeatured: false,
  },
];

export const INITIAL_TONTINE_GROUPS: TontineGroup[] = [
  {
    id: 'tnt-group-tv-55',
    code: 'TNT-TV-01',
    title: 'Tontine Smart TV Samsung 55" 4K',
    description: 'Groupe d\'épargne rotative pour équiper son salon de la Smart TV 55" Samsung Crystal UHD.',
    targetProductId: 'prod-samsung-tv-55-4k',
    targetProductName: 'Smart TV Samsung 55" Crystal UHD 4K',
    targetProductPrice: 310000,
    targetProductImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    frequency: 'monthly',
    totalPositions: 10,
    filledPositions: 7,
    contributionAmount: 31000,
    totalTargetAmount: 310000,
    durationCycles: 10,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-15',
    rulesDescription: 'Chaque membre cotise 31 000 FCFA par mois. À chaque tirage mensuel, un membre reçoit sa TV neuve livrée à domicile avec garantie officielle PENTA GAD.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tnt-group-fridge-260',
    code: 'TNT-FRIG-02',
    title: 'Tontine Réfrigérateur Combiné Hisense 260L',
    description: 'Formule rotative 6 personnes pour acquérir le réfrigérateur Hisense No Frost sans impacter son budget familial.',
    targetProductId: 'prod-hisense-fridge-260',
    targetProductName: 'Réfrigérateur Combiné No Frost Hisense 260L',
    targetProductPrice: 228000,
    targetProductImage: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    frequency: 'monthly',
    totalPositions: 6,
    filledPositions: 4,
    contributionAmount: 38000,
    totalTargetAmount: 228000,
    durationCycles: 6,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-20',
    rulesDescription: '6 mensualités de 38 000 FCFA. Tirage au sort ou ordre transparent fixé au lancement. Livraison immédiate lors de votre tour.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tnt-group-clim-midea',
    code: 'TNT-CLIM-03',
    title: 'Tontine Climatiseur Split Inverter 1.5 CV',
    description: 'Anticipez la saison des chaleurs avec un climatiseur Inverter économe en énergie.',
    targetProductId: 'prod-midea-split-15cv',
    targetProductName: 'Climatiseur Split Midea 1.5 CV Inverter',
    targetProductPrice: 246000,
    targetProductImage: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80',
    frequency: 'monthly',
    totalPositions: 6,
    filledPositions: 5,
    contributionAmount: 41000,
    totalTargetAmount: 246000,
    durationCycles: 6,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-10',
    rulesDescription: 'Installation offerte à Abidjan pour les participants du groupe PENTA GAD.',
    createdAt: new Date().toISOString(),
  },
];
