import { Category, Product, TontineGroup } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-electromenager',
    name: 'Électroménager',
    slug: 'electromenager',
    description: 'Réfrigérateurs, congélateurs, lave-linge et cuisinières de grandes marques tropicalisées.',
    icon: 'Refrigerator',
    displayOrder: 1,
    isActive: true,
    itemCount: 14,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-tv-audio',
    name: 'Téléviseurs & Audio',
    slug: 'tv-audio',
    description: 'Smart TV UHD 4K, barres de son immersives et équipements audiovisuels.',
    icon: 'Tv',
    displayOrder: 2,
    isActive: true,
    itemCount: 10,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-climatisation',
    name: 'Climatisation & Ventilation',
    slug: 'climatisation',
    description: 'Climatiseurs split inverter économiques, rafraîchisseurs et ventilateurs puissants.',
    icon: 'Wind',
    displayOrder: 3,
    isActive: true,
    itemCount: 8,
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-mobilier',
    name: 'Mobilier de Maison',
    slug: 'mobilier',
    description: 'Salons en velours et cuir, salles à manger, lits capitonnés et rangements modernes.',
    icon: 'Armchair',
    displayOrder: 4,
    isActive: true,
    itemCount: 12,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cat-cuisine-maison',
    name: 'Équipements & Petit Ménager',
    slug: 'equipements-maison',
    description: 'Micro-ondes, fontaines à eau, mixeurs, fers à repasser et accessoires indispensables.',
    icon: 'Coffee',
    displayOrder: 5,
    isActive: true,
    itemCount: 18,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-hisense-fridge-260',
    reference: 'PG-REF-1001',
    name: 'Réfrigérateur Combiné No Frost Hisense 260L',
    slug: 'refrigerateur-combine-no-frost-hisense-260l',
    shortDescription: 'Réfrigérateur combiné haut de gamme tropicalisé avec technologie Total No Frost et distributeur d\'eau en façade.',
    fullDescription: 'Conçu spécialement pour résister aux chaleurs et à l\'humidité d\'Abidjan et des régions de Côte d\'Ivoire, ce réfrigérateur Hisense 260L intègre un compresseur tropicalisé ultra-silencieux. La technologie Total No Frost évite la formation de givre, préservant ainsi la fraîcheur et les qualités nutritives de vos aliments sans besoin de dégivrage manuel.',
    description: 'Réfrigérateur combiné haut de gamme avec technologie No Frost intégrée, distributeur d\'eau en façade et compresseur tropicalisé.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Hisense',
    model: 'RD-35WR',
    price: 215000,
    priceCash: 215000,
    oldPrice: 235000,
    promotionalPrice: 215000,
    priceInstallment: 235000,
    priceTontine: 228000,
    stock: 12,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1536353284924-9240ccfc4966?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Capacité totale 260 Litres',
      'Technologie Total No Frost (anti-givre automatique)',
      'Distributeur d\'eau fraîche intégré en façade sans raccordement requis',
      'Éclairage LED basse consommation et silencieux',
      'Portes réversibles avec joints antibactériens',
      'Garantie 2 ans constructeur avec SAV PENTA GAD Abidjan',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
    createdAt: '2026-09-15T10:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-samsung-tv-55-4k',
    reference: 'PG-REF-1002',
    name: 'Smart TV Samsung 55" Crystal UHD 4K',
    slug: 'smart-tv-samsung-55-crystal-uhd-4k',
    shortDescription: 'Qualité d\'image 4K saisissante avec processeur Crystal, compatible Netflix, YouTube, Canal+ et son Dolby Audio.',
    fullDescription: 'Plongez au cœur de l\'action avec la Smart TV Samsung 55 pouces (140 cm) Crystal UHD. Son puissant processeur optimise chaque scène en résolution 4K avec des couleurs éclatantes et un contraste dynamique. Grâce au système Tizen fluide, accédez à toutes vos applications de streaming préférées directement avec votre connexion Wi-Fi.',
    description: 'Une qualité d\'image saisissante avec le processeur Crystal 4K, compatible Netflix, YouTube, Canal+, et son Dolby Digital immersif.',
    categoryId: 'cat-tv-audio',
    categoryName: 'Téléviseurs & Audio',
    brand: 'Samsung',
    model: 'UA55CU7000',
    price: 295000,
    priceCash: 295000,
    oldPrice: 325000,
    promotionalPrice: 295000,
    priceInstallment: 320000,
    priceTontine: 310000,
    stock: 9,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Écran 55 pouces (140 cm) 4K Ultra Haute Définition (3840 x 2160)',
      'HDR 10+ et technologie PurColor pour des teintes naturelles',
      'Système d\'exploitation Tizen OS avec boutique d\'applications complète',
      'Connectivité complète : 3 ports HDMI, 1 port USB, Bluetooth 5.2, Wi-Fi 5',
      'Audio 20W avec technologie Object Tracking Sound Lite',
      'Garantie officielle 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 20,
    isActive: true,
    isFeatured: true,
    createdAt: '2026-09-18T11:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-midea-split-15cv',
    reference: 'PG-REF-1003',
    name: 'Climatiseur Split Midea 1.5 CV Inverter Tropicalisé',
    slug: 'climatiseur-split-midea-1-5-cv-inverter',
    shortDescription: 'Climatiseur split inverter silencieux et ultra économe en électricité (jusqu\'à 60% d\'économie) avec gaz R32.',
    fullDescription: 'Le climatiseur Split Midea 1.5 CV Inverter (12 000 BTU) est la référence absolue pour rafraîchir rapidement salon ou chambre principale. Son compresseur Inverter à vitesse variable ajuste en permanence la puissance pour maintenir la température souhaitée tout en réduisant considérablement la facture d\'électricité de la CIE.',
    description: 'Climatiseur split inverter haute efficacité énergétique, conçu spécialement pour le climat chaud et humide d\'Abidjan.',
    categoryId: 'cat-climatisation',
    categoryName: 'Climatisation & Ventilation',
    brand: 'Midea',
    model: 'MSAF-12CRDN1',
    price: 235000,
    priceCash: 235000,
    oldPrice: 250000,
    priceInstallment: 255000,
    priceTontine: 245000,
    stock: 15,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Puissance thermique 1.5 CV (12 000 BTU/h)',
      'Moteur Inverter de pointe : réduction jusqu\'à 60% de consommation électrique',
      'Fluide frigorigène écologique R32 à haute performance calorifique',
      'Filtre haute densité antibactérien et anti-poussière lavable',
      'Mode Turbo pour refroidissement ultra-rapide en 30 secondes',
      'Garantie 3 ans sur le compresseur',
    ],
    warrantyMonths: 36,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
    createdAt: '2026-09-20T09:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-solstar-cooker-4f',
    reference: 'PG-REF-1004',
    name: 'Cuisinière 4 Feux Inox Solstar avec Four Grill',
    slug: 'cuisiniere-4-feux-inox-solstar',
    shortDescription: 'Cuisinière tout inox robuste avec 4 brûleurs à allumage intégré, tournebroche et grand four à gaz.',
    fullDescription: 'Robuste, élégante et sécurisée, la cuisinière Solstar 4 feux inox est conçue pour supporter un usage culinaire intensif. Elle possède des chapeaux de brûleur en fonte émaillée, un allumage électrique à une main et un grand four avec tournebroche rôtissoire pour préparer vos plats familiaux.',
    description: 'Cuisinière à gaz en acier inoxydable robuste avec 4 brûleurs haute puissance, grand four émaillé et grille chauffante.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Solstar',
    model: 'FS-6060-IX',
    price: 145000,
    priceCash: 145000,
    oldPrice: 160000,
    priceInstallment: 160000,
    priceTontine: 155000,
    stock: 8,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Dimensions 60 x 60 cm compactes et spacieuses',
      'Finition carrosserie et table en inox brossé anti-corrosion',
      '4 brûleurs gaz haute performance dont un grand brûleur rapide',
      'Four émaillé avec éclairage interne, minuterie et tournebroche',
      'Couvercle rabattable en verre trempé renforcé',
      'Garantie 1 an pièce et main d\'œuvre',
    ],
    warrantyMonths: 12,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 4,
    installmentMinDepositPercent: 30,
    isActive: true,
    isFeatured: false,
    createdAt: '2026-09-22T14:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-lg-washer-8kg',
    reference: 'PG-REF-1005',
    name: 'Lave-linge Automatique LG 8kg Direct Drive',
    slug: 'lave-linge-automatique-lg-8kg',
    shortDescription: 'Lave-linge frontal 8 kg avec moteur Inverter Direct Drive garanti 10 ans, lavage vapeur et essorage 1200 trs/min.',
    fullDescription: 'Prenez soin de vos vêtements avec le lave-linge LG 8kg. Son moteur sans courroie Inverter Direct Drive fixé directement au tambour élimine les bruits de vibration et assure une fiabilité exceptionnelle. Les programmes vapeur éliminent 99.9% des allergènes et acariens.',
    description: 'Machine à laver automatique avec moteur Inverter Direct Drive ultra fiable, lavage vapeur anti-allergène et essorage 1200 tours/min.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'LG',
    model: 'FH2J3TDNP0',
    price: 310000,
    priceCash: 310000,
    oldPrice: 340000,
    promotionalPrice: 310000,
    priceInstallment: 335000,
    priceTontine: 325000,
    stock: 6,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Capacité de lavage 8 kg idéale pour les familles',
      'Technologie 6 Motion DD : 6 mouvements de tambour adaptés au tissu',
      'Moteur Inverter Direct Drive ultra silencieux garanti 10 ans',
      'Vitesse d\'essorage réglable jusqu\'à 1200 tours par minute',
      'Classe d\'efficacité énergétique A+++ pour économiser l\'eau et l\'électricité',
      'Garantie globale 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 20,
    isActive: true,
    isFeatured: true,
    createdAt: '2026-09-24T09:30:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-penta-salon-confort',
    reference: 'PG-REF-1006',
    name: 'Salon d\'Angle Modulaire 6 Places PENTA Confort',
    slug: 'salon-angle-modulaire-6-places-penta',
    shortDescription: 'Canapé d\'angle moderne en velours déperlant antitaches avec mousse haute résilience grand confort.',
    fullDescription: 'Sublimez votre séjour avec le salon d\'angle PENTA Confort 6 places. Fabriqué avec une ossature robuste en bois dur traité contre les insectes xylophages, il est habillé d\'un tissu velours antitaches doux au toucher et facile d\'entretien. La méridienne est réversible pour s\'adapter à l\'agencement de votre pièce.',
    description: 'Ensemble salon d\'angle moderne en tissu velours antitaches avec mousse haute résilience grand confort, table basse assortie offerte.',
    categoryId: 'cat-mobilier',
    categoryName: 'Mobilier de Maison',
    brand: 'PENTA Living',
    model: 'PL-ANG-06',
    price: 450000,
    priceCash: 450000,
    oldPrice: 490000,
    priceInstallment: 490000,
    priceTontine: 480000,
    stock: 4,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Capacité 6 grandes places assises avec coussins d\'assise et dossiers généreux',
      'Structure en bois massif séché et traité sous pression',
      'Mousse haute résilience densité 32 kg/m³ garantissant une tenue sans affaissement',
      'Tissu velours traité déperlant (les liquides perlent sans pénétrer)',
      'Table basse moderne assortie incluse dans l\'offre',
      'Garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 8,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: true,
    createdAt: '2026-09-25T16:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-westpool-freezer-200',
    reference: 'PG-REF-1007',
    name: 'Congélateur Coffre Westpool 200 Litres Tropicalisé',
    slug: 'congelateur-coffre-westpool-200l',
    shortDescription: 'Congélateur horizontal super isolé avec autonomie de froid prolongée jusqu\'à 48h et serrure à clé.',
    fullDescription: 'Idéal pour le stockage de vivres, poissons et viandes, ce congélateur coffre Westpool 200 Litres offre une congélation rapide et une isolation renforcée à haute densité qui garde le froid jusqu\'à 48 heures en cas de coupure de courant. Son condenseur extérieur dissipe efficacement la chaleur.',
    description: 'Congélateur horizontal super isolé maintenant le froid jusqu\'à 48h en cas de coupure d\'électricité.',
    categoryId: 'cat-electromenager',
    categoryName: 'Électroménager',
    brand: 'Westpool',
    model: 'BD-200',
    price: 175000,
    priceCash: 175000,
    oldPrice: 195000,
    priceInstallment: 190000,
    priceTontine: 185000,
    stock: 11,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Volume utile 200 Litres',
      'Parois épaisses isolantes en polyuréthane haute densité',
      'Thermostat mécanique réglable en façade avec voyant lumineux',
      'Panier suspendu métallique amovible pour petits articles',
      'Poignée ergonomique avec serrure à clé intégrée',
      'Garantie 2 ans',
    ],
    warrantyMonths: 24,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: true,
    installmentMaxMonths: 6,
    installmentMinDepositPercent: 25,
    isActive: true,
    isFeatured: false,
    createdAt: '2026-09-26T10:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'prod-fontaine-eau-penta',
    reference: 'PG-REF-1008',
    name: 'Fontaine Distributrice d\'Eau Chaude & Froide PENTA',
    slug: 'fontaine-distributrice-eau-penta',
    shortDescription: 'Distributeur d\'eau sur pied avec compartiment réfrigéré inférieur et robinets chaud/froid sécurisés.',
    fullDescription: 'Offrez-vous de l\'eau fraîche ou instantanément chaude pour vos thés et cafés à la maison ou au bureau. Cette fontaine PENTA Appliances dispose d\'un compresseur frigorifique performant et d\'un compartiment de stockage réfrigéré dans sa partie basse.',
    description: 'Distributeur d\'eau sur pied élégant avec compartiment réfrigéré inférieur, robinets sécurisés eau chaude et froide.',
    categoryId: 'cat-cuisine-maison',
    categoryName: 'Équipements & Petit Ménager',
    brand: 'PENTA Appliances',
    model: 'WD-201',
    price: 65000,
    priceCash: 65000,
    oldPrice: 75000,
    priceInstallment: 75000,
    priceTontine: 70000,
    stock: 20,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
    ],
    features: [
      'Double robinet : eau glacée (5°C à 10°C) et eau chaude (85°C à 95°C)',
      'Sécurité enfant renforcée sur le robinet d\'eau chaude',
      'Compartiment réfrigérateur d\'appoint 16 Litres en partie basse',
      'Réservoir en acier inoxydable alimentaire antibactérien',
      'Garantie 1 an',
    ],
    warrantyMonths: 12,
    isCashEligible: true,
    isInstallmentEligible: true,
    isTontineEligible: false,
    installmentMaxMonths: 3,
    installmentMinDepositPercent: 30,
    isActive: true,
    isFeatured: false,
    createdAt: '2026-09-28T12:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
];

export const INITIAL_TONTINE_GROUPS: TontineGroup[] = [
  {
    id: 'tnt-group-tv-55',
    groupCode: 'TG-001',
    name: 'Tontine Smart TV Samsung 55" 4K',
    code: 'TG-001',
    title: 'Tontine Smart TV Samsung 55" 4K',
    description: 'Groupe d\'épargne rotative pour équiper son salon de la Smart TV 55" Samsung Crystal UHD.',
    targetProductId: 'prod-samsung-tv-55-4k',
    targetProductName: 'Smart TV Samsung 55" Crystal UHD 4K',
    targetProductPrice: 310000,
    targetProductImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    memberCount: 10,
    rotationPeriodDays: 10,
    totalDurationDays: 110,
    contributionFrequency: 'daily',
    totalPositions: 10,
    filledPositions: 7,
    contributionAmount: 31000,
    totalTargetAmount: 310000,
    durationCycles: 10,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-15',
    endDate: '2027-02-02',
    rulesDescription: 'Chaque membre cotise 31 000 FCFA par mois. À chaque tirage mensuel, un membre reçoit sa TV neuve livrée à domicile avec garantie officielle PENTA GAD.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tnt-group-fridge-260',
    groupCode: 'TG-002',
    name: 'Tontine Réfrigérateur Combiné Hisense 260L',
    code: 'TG-002',
    title: 'Tontine Réfrigérateur Combiné Hisense 260L',
    description: 'Formule rotative 10 personnes pour acquérir le réfrigérateur Hisense No Frost sans impacter son budget familial.',
    targetProductId: 'prod-hisense-fridge-260',
    targetProductName: 'Réfrigérateur Combiné No Frost Hisense 260L',
    targetProductPrice: 228000,
    targetProductImage: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    memberCount: 10,
    rotationPeriodDays: 10,
    totalDurationDays: 110,
    contributionFrequency: 'daily',
    totalPositions: 10,
    filledPositions: 4,
    contributionAmount: 22800,
    totalTargetAmount: 228000,
    durationCycles: 10,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-20',
    endDate: '2027-02-07',
    rulesDescription: 'Tirage au sort ou ordre transparent fixé au lancement. Livraison immédiate lors de votre tour.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tnt-group-clim-midea',
    groupCode: 'TG-003',
    name: 'Tontine Climatiseur Split Inverter 1.5 CV',
    code: 'TG-003',
    title: 'Tontine Climatiseur Split Inverter 1.5 CV',
    description: 'Anticipez la saison des chaleurs avec un climatiseur Inverter économe en énergie.',
    targetProductId: 'prod-midea-split-15cv',
    targetProductName: 'Climatiseur Split Midea 1.5 CV Inverter',
    targetProductPrice: 246000,
    targetProductImage: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80',
    memberCount: 10,
    rotationPeriodDays: 10,
    totalDurationDays: 110,
    contributionFrequency: 'daily',
    totalPositions: 10,
    filledPositions: 5,
    contributionAmount: 24600,
    totalTargetAmount: 246000,
    durationCycles: 10,
    currentCycle: 1,
    status: 'open',
    startDate: '2026-10-10',
    endDate: '2027-01-28',
    rulesDescription: 'Installation offerte à Abidjan pour les participants du groupe PENTA GAD.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
